data_path: data/1140.csv
end_date: '2024-09-28'
epochs: 1
future_hours: 24
model: LSR
model_complexity: baseline
past_days: 3
past_hours: 72
plot_days: 7
save_dir: temp_results/1140/LSR_low_NWP_plus_72h_TE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params: {}
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_pv: false
use_time_encoding: true
val_ratio: 0.1
weather_category: forecast_ideal
