data_path: data/Project1140.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 1
future_hours: 24
model: Linear
model_complexity: low
model_params:
  ml_high:
    learning_rate: 0.001
  ml_low:
    learning_rate: 0.001
past_days: 1
past_hours: 24
plot_days: 7
save_dir: temp_results/1140/LSR_low_NWP_plus_24h_noTE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params: {}
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_ideal_nwp: true
use_pv: false
use_time_encoding: false
val_ratio: 0.1
weather_category: all_weather
