data_path: data/Project1140.csv
end_date: '2024-09-28'
epochs: 50
future_hours: 24
model: LSTM
model_complexity: high
model_params:
  high:
    d_model: 256
    dropout: 0.3
    hidden_dim: 128
    num_heads: 16
    num_layers: 18
past_days: 3
past_hours: 72
plot_days: 7
save_dir: temp_results/1140/LSTM_high_PV_plus_NWP_72h_noTE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  d_model: 256
  dropout: 0.3
  hidden_dim: 128
  num_heads: 16
  num_layers: 18
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_pv: true
use_time_encoding: false
val_ratio: 0.1
weather_category: forecast
