data_path: data/Project1140.csv
end_date: '2024-09-28'
epochs: 15
future_hours: 24
model: RF
model_complexity: low
model_params:
  ml_high:
    learning_rate: 0.01
    max_depth: 12
    n_estimators: 200
  ml_low:
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 50
past_days: 1
past_hours: 24
plot_days: 7
save_dir: temp_results/1140/RF_low_PV_plus_NWP_plus_24h_TE
save_options:
  save_excel_results: true
  save_model: false
  save_predictions: true
  save_summary: false
  save_training_log: true
start_date: '2022-01-01'
train_params: {}
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_ideal_nwp: true
use_pv: true
use_time_encoding: true
val_ratio: 0.1
weather_category: all_weather
