data_path: data/Project1140.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 80
future_hours: 24
model: TCN
model_complexity: high
model_params:
  high:
    dropout: 0.3
    kernel_size: 5
    tcn_channels:
    - 64
    - 128
    - 256
  low:
    dropout: 0.1
    kernel_size: 3
    tcn_channels:
    - 32
    - 64
past_days: 1
past_hours: 24
plot_days: 7
save_dir: temp_results/1140/TCN_high_PV_plus_NWP_24h_noTE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  batch_size: 64
  learning_rate: 0.001
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_pv: true
use_time_encoding: false
val_ratio: 0.1
weather_category: all_weather
