data_path: ./data/Project65.csv
end_date: '2024-09-28'
epochs: 15
forecast_features: []
future_hours: 24
model: LSTM
model_complexity: low
past_days: 1
past_hours: 24
plot_days: 7
save_dir: ./temp_results/Project65
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  d_model: 64
  dropout: 0.1
  hidden_dim: 32
  num_heads: 4
  num_layers: 6
train_ratio: 0.8
use_forecast: false
use_hist_weather: true
use_pv: true
use_time_encoding: false
val_ratio: 0.1
weather_features:
- global_tilted_irradiance
- vapour_pressure_deficit
- relative_humidity_2m
- temperature_2m
- wind_gusts_10m
- cloud_cover_low
- wind_speed_100m
- snow_depth
- dew_point_2m
- precipitation
- surface_pressure
