data_path: ./data/Project9.csv
end_date: '2024-09-28'
epochs: 50
forecast_features: []
future_hours: 24
model: TCN
model_complexity: high
past_days: 3
past_hours: 72
plot_days: 7
save_dir: ./temp_results/Project9
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  d_model: 256
  dropout: 0.3
  hidden_dim: 128
  num_heads: 16
  num_layers: 18
train_ratio: 0.8
use_forecast: false
use_hist_weather: true
use_pv: true
use_time_encoding: true
val_ratio: 0.1
weather_features:
- global_tilted_irradiance
- vapour_pressure_deficit
- relative_humidity_2m
- temperature_2m
- wind_gusts_10m
- cloud_cover_low
- wind_speed_100m
- snow_depth
- dew_point_2m
- precipitation
- surface_pressure
