data_path: ./data/Project82.csv
end_date: '2024-09-28'
epochs: 15
forecast_features: []
future_hours: 24
model: XGB
model_complexity: low
past_days: 3
past_hours: 72
plot_days: 7
save_dir: ./temp_results/Project82
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 50
train_ratio: 0.8
use_forecast: false
use_hist_weather: false
use_pv: true
use_time_encoding: false
val_ratio: 0.1
weather_features: []
