data_path: data/Project1140.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 50
future_hours: 24
model: TCN
model_complexity: low
model_params:
  high:
    d_model: 256
    dropout: 0.3
    hidden_dim: 128
    num_heads: 16
    num_layers: 18
  low:
    d_model: 64
    dropout: 0.1
    hidden_dim: 32
    num_heads: 4
    num_layers: 6
past_days: 3
past_hours: 24
plot_days: 7
save_dir: temp_results/171/TCN_low_NWP_plus_24h_TE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  batch_size: 64
  learning_rate: 0.001
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_ideal_nwp: true
use_pv: false
use_time_encoding: true
val_ratio: 0.1
weather_category: all_weather
