data_path: data/Project171.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 50
future_hours: 24
model: XGB
model_complexity: high
model_params:
  high:
    colsample_bytree: 0.8
    learning_rate: 0.1
    max_depth: 10
    n_estimators: 200
    random_state: 42
    subsample: 0.8
  low:
    colsample_bytree: 0.9
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
    subsample: 0.9
past_days: 3
past_hours: 72
plot_days: 7
save_dir: temp_results/171/XGB_high_PV_plus_HW_72h_noTE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  batch_size: 64
  learning_rate: 0.001
train_ratio: 0.8
use_forecast: false
use_hist_weather: true
use_ideal_nwp: false
use_pv: true
use_time_encoding: false
val_ratio: 0.1
weather_category: hist_weather
