# config/default.yaml

# Data & output paths
data_path: './data/Project1033.csv'  # 数据文件路径
save_dir:   './result'               # 结果保存目录

# Model selection & ablation
model: 'Transformer'      # options: Transformer, LSTM, GRU, TCN, RF, XGB, LGBM

# Time window options (消融实验)
past_days: 3              # options: 1, 3, 7 (历史天数)
future_hours: 24          # 预测小时数
past_hours: 72            # 自动计算: past_days * 24

# Feature options
use_hist_weather: false   # use history weather features
use_forecast: false       # include weather forecasts (Open-Meteo forecast API)
# Note: Time encodings (month/hour sin/cos) are always included

# Data split ratios
train_ratio: 0.8          # fraction for training set
val_ratio:   0.1          # fraction for validation set (test = 1 - train - val)

# Plotting options
plot_days: 7              # number of days to plot in forecast

# Model-specific parameters (消融实验: low/medium/high)
model_complexity: 'medium'  # options: low, medium, high

model_params:
  # Transformer / DL parameters by complexity
  low:
    d_model:       32
    num_heads:      2
    num_layers:     2
    hidden_dim:     64
    dropout:        0.1
    tcn_channels:   [32, 32]
    kernel_size:    3
  
  medium:
    d_model:       64
    num_heads:      4
    num_layers:     4
    hidden_dim:     128
    dropout:        0.1
    tcn_channels:   [64, 64]
    kernel_size:    3
  
  high:
    d_model:       128
    num_heads:      8
    num_layers:     6
    hidden_dim:     256
    dropout:        0.1
    tcn_channels:   [128, 128, 64]
    kernel_size:    3

  # ML parameters by complexity
  ml_low:
    n_estimators:  50
    max_depth:      5
    learning_rate:  0.1
    random_state:   42
  
  ml_medium:
    n_estimators:  100
    max_depth:      15
    learning_rate:  0.1
    random_state:   42
  
  ml_high:
    n_estimators:  200
    max_depth:      25
    learning_rate:  0.05
    random_state:   42

# Training parameters
train_params:
  batch_size:           32
  learning_rate:        1e-3
  loss_type:            'mse'    # options: 'mse'
  future_hours:         24

# Epoch parameters by complexity (消融实验)
epoch_params:
  low:     15    # 简单模型，较少epoch
  medium:  30    # 中等模型，适中epoch
  high:    50    # 复杂模型，更多epoch

# 保存选项
save_options:
  save_model:           false    # 是否保存模型文件
  save_summary:         true     # 是否保存summary.csv
  save_predictions:     false    # 是否保存predictions.csv (默认不保存)
  save_training_log:    false    # 是否保存training_log.csv (仅DL模型，默认不保存)
  save_forecast_plot:   false    # 是否保存forecast_plots.png
  save_training_curve:  false    # 是否保存training_curve.png (仅DL模型，默认不保存)
  save_excel_results:   true     # 是否保存Excel结果文件
