# config/project1033_test.yaml
# Project1033单厂测试配置 - 不保存预测结果文件

# Data & output paths
data_path: './data/Project1033.csv'  # 数据文件路径
save_dir:   '/content/drive/MyDrive/Solar PV electricity/result_new'  # 结果保存目录

# Model selection & ablation
model: 'Transformer'      # options: Transformer, LSTM, GRU, TCN, RF, XGB, LGBM, Linear

# Time window options (消融实验)
past_days: 3              # options: 1, 3 (历史天数)
future_hours: 24          # 预测小时数
past_hours: 72            # 自动计算: past_days * 24

# Feature options
use_pv: true              # 使用历史PV发电量数据
use_hist_weather: false   # use history weather features
use_forecast: false       # include weather forecasts (Open-Meteo forecast API)
weather_category: 'irradiance'  # weather feature category: irradiance, all_weather
use_time_encoding: true   # use time encoding features (month/hour sin/cos)

# Data split ratios
train_ratio: 0.8          # fraction for training set
val_ratio:   0.1          # fraction for validation set (test = 1 - train - val)

# Plotting options
plot_days: 7              # number of days to plot in forecast

# Model-specific parameters (消融实验: low/high)
model_complexity: 'low'  # options: low, high

model_params:
  # Transformer / DL parameters by complexity
  low:
    d_model:       64
    num_heads:      4
    num_layers:     3
    hidden_dim:     128
    dropout:        0.2
    tcn_channels:   [64, 64, 32]
    kernel_size:    3
  
  high:
    d_model:       128
    num_heads:      8
    num_layers:     6
    hidden_dim:     256
    dropout:        0.2
    tcn_channels:   [128, 128, 64, 32]
    kernel_size:    3

  # ML parameters by complexity
  ml_low:
    n_estimators:  100
    max_depth:      10
    learning_rate:  0.1
    random_state:   42
  
  ml_high:
    n_estimators:  300
    max_depth:      20
    learning_rate:  0.05
    random_state:   42

# Training parameters
train_params:
  batch_size:           32
  learning_rate:        5e-4     # 降低学习率
  loss_type:            'mse'    # options: 'mse'
  future_hours:         24

# Epoch parameters by complexity (消融实验)
epoch_params:
  low:     30    # 简单模型，适中epoch
  high:    60    # 复杂模型，更多epoch

# 保存选项 - 不保存预测结果文件
save_options:
  save_model:           false    # 是否保存模型文件
  save_summary:         false    # 已禁用summary.csv保存
  save_predictions:     false    # 不保存predictions.csv
  save_training_log:    false    # 不保存training_log.csv
  # 绘图功能已移除，默认不保存图片
  save_excel_results:   true     # 只保存Excel结果文件
