data_path: ./Project1140.csv
save_dir: ./results/ablation
future_hours: 24
train_ratio: 0.8
val_ratio: 0.1
plot_days: 7
start_date: '2022-01-01'
end_date: '2024-09-28'
train_params:
  batch_size: 32
  learning_rate: 0.0005
  loss_type: mse
  future_hours: 24
save_options:
  save_model: false
  save_summary: true
  save_predictions: true
  save_training_log: false
  save_excel_results: true
past_hours: 24
use_time_encoding: false
weather_category: ablation_11_features
use_pv: true
use_hist_weather: true
use_forecast: false
input_category: PV_plus_HW
model: LSR
model_complexity: low
epoch_params:
  low: 1
  high: 1
model_params:
  low:
    fit_intercept: true
  high:
    fit_intercept: true
