data_path: data/Project186.csv
end_date: '2024-09-28'
epoch_params:
  high: 80
  low: 50
epochs: 50
future_hours: 24
model: RF
model_complexity: low
model_params:
  high:
    max_depth: 20
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 200
    random_state: 42
  low:
    max_depth: 10
    min_samples_leaf: 2
    min_samples_split: 5
    n_estimators: 100
    random_state: 42
past_days: 3
past_hours: 72
plot_days: 7
save_dir: temp_results/186/RF_low_NWP_plus_72h_noTE
save_options:
  save_excel_results: false
  save_model: false
  save_predictions: false
  save_summary: false
  save_training_log: false
start_date: '2022-01-01'
train_params:
  batch_size: 64
  learning_rate: 0.001
train_ratio: 0.8
use_forecast: true
use_hist_weather: false
use_ideal_nwp: true
use_pv: false
use_time_encoding: false
val_ratio: 0.1
weather_category: nwp_plus
